In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import re
import tensorflow as tf
from konlpy.tag import Okt
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

# 형태소 분석


In [2]:
dic = pd.read_csv('comment.csv',encoding = 'cp949')
comment_data = dic[['comment']] 
X_data = comment_data['comment']

In [3]:
normalized_text = []
for string in X_data.tolist():
    try:
        tokens = re.sub(r"[^ㄱ-ㅎㅏ-ㅣ가-힣\?\.!]+", " ", string.lower())
    except Exception as e:
        print(string)
        break
    normalized_text.append(tokens)
print(normalized_text[:5])

['정말 노래 대단하네요', '가창력 대단하고.인기도 굉장해요.연예계의 별이 될꺼 같아요', '노래만큼은 정말 넘사벽 맞다. 최고 맞다. ', '진짜 잘하네용', '노래 정말잘해']


In [4]:
comment_data.comment = normalized_text
for sentence in comment_data['comment']:
    print(sentence)

정말 노래 대단하네요
가창력 대단하고.인기도 굉장해요.연예계의 별이 될꺼 같아요
노래만큼은 정말 넘사벽 맞다. 최고 맞다. 
진짜 잘하네용
노래 정말잘해
티비 보는데 진짜 잘하긴 잘하네요
소름돋네요. 방송사에서 이케 파격대우하다니. 아무나 해주지 않쵸.
정말 타고났다는 말밖엔 표현할 방법이없다 대박이다 대박
지금 콘서트 방송 보고있는데 진짜 최고
신곡 좋네요
정말 대단합니다. 엄청난 임팩트 . 카리스마 대단해요. 
직접 보진 못했지만 방송으로 설겆이도 미뤄둔채 본방사수중입니다 들을수록 정이가는 음색입니다.꾸준하게 열심히 노래 부러세요 
다른 가수 저 레파토리로 할수있는 사람없다 퀄리티좀봐라
정말 연예계의 별이네요 가창력도 대단하시고 너무 멋있으세요 카리스마도 엄청나시고 얼굴도 복스럽게 생기셔서 나이 상관없이 모두에게 사랑받으시는거같아요 존경합니다
최고네요
와 팬덤 장난 아이네요 노래도 정말 잘하구요
노래 정말 정말 잘하는 가수가 나타났다 짱 멋집니다
신곡 넘 좋아요. 완전팬 되었습니다.
노래 천재
와..진짜 티비 보면서도 울었습니다.백만녀만에 한번 나올까말까 한 가수라는게 맞는듯
 신경좀 썼네!! 감동이다!!!!
너무 잘하네요. 신곡도 너무좋고 ?넘 좋음 너무 인상도좋고 사랑스러움
울컥. 대박 기원
역사에 한획을 그은 가수임에 틀림없다..가슴이 아리다.. 음색에는 뭔가 특별한 뭔가가 있다...
중계볼려고 오늘 팔공산갓바위 갔다가 빨리 절하고 집에 온 인
대박 쳤다 
우와 대박!!!잘하네 잘해
진짜 엄마 아부지는 얼마나 행복하까
와..노래 하는 걸 제대로 처음 들었는데 왜 인기를 이렇게나 많이 받으시는지 알았습니다. 와 모라고 표현하고 싶은데.. 그냥 대박이네요 마음이 훈훈해지고 진심 더 좋습니다..! 응원합니다. 좋은 목소리 좋은 노래 좋은 음악 감사합니다 !
넘 좋아요. 눈물 나네요. 언제나 변함없이 응원합니다 사랑합니다 
진짜대단하네 
막힘없는 가창력 최고네요
온가족 시청중 너무 잘해요 인상도 너무 좋고
 세기 최고의 가수가 우리에게 나타났습니다. 우리곁에

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value



그냥 다 부럽다
역시 여신이십니다
매번 리즈갱신 
아이구 이뻐라 저보다 한살 위인데 너무 동안이에요 부럽다능 ㅎ
화이팅 화이팅
이쁘네요 역시 잘 어울려요
나는 노화하는데 이 분은 진화해
완전 인형 !!!!넘나 이뻐요 
진짜 겁나 이쁨.
진짜 무엇... 머리를 미셔도 아름다우실 듯ㅠㅠㅠㅠㅠ
진짜 너무 이쁘다
진심 넘넘사랑스러워 
역시 여신 뭘하든 다 왼벽해.. 정말 부러운 여자
존예....
역쉬여신
모든게 완벽한 여신
사진보고 할말이 없다.. 너무 이쁘다
기냥 이쁘네
이쁜 건 정말 인정.
예쁜건 인정. 
인형보다 이쁘다....
얼굴은 우리나라 탑인거 같다
여신 인정
왜 사람들이 예쁘다하는지 알겠다! 귀티가 흐르네 흘러
독특한 아름다움 부러워..
실물 봤는데 미치도록 이쁘더라
얼굴은 미쳤다...그냥 등
배우 중 최고 어떤수식어로도 부족하다 아름다움 그 자체!!
배우중 최고인 듯...
다 이쁘다ㅠ
미모갱신중... 내배우 넘 아름다우세요 항상 리즈시군요 
그모습 넘 아까우니 좋은 작품으로 얼른 와줘요 연기하는 모습 너무 보고 싶어요
진심 이쁨
정말정말 데뷔때부터 안이쁜적이 없어요
너무 이뿌다
내가 가장좋아하는 연예인
태어났을때부터 완성형이더라
이쁜데 고급지게 이쁨
결혼 하시더니 아름다움이 배가 되는 듯
살이 빠졌나?
참 예뻐 스타일 변신도 늘 과감해서 질리지 않게 이쁨 
예쁘다란 말로 부족해 클라스가 다른 미모. 남의 여자지만 진심 미치게 하는 미모
진짜 인형이라고 하더니 실물 한번 봤으면 좋겠다 정말 예뻐요
와 진짜 가끔 깜짝 놀랄정도로 예쁨 
누가봐도 이쁜데. 알바 풀 필요 없는데.
인정 
우아하면서 고급스럽게 예쁘네요
와
너무 이뻐요.
나이들수록이뻐지는게신기
인형이다 진짜 자연미인
진짜 예쁘다
항상 이쁠 여인 이쁘다 
예쁘긴 예쁘다
기가 막힌다 참 어찌 저리 이쁠꼬
가끔 이런 화장도 좋네 이뻐 섹시하고
비교불가 미모
진짜 예쁘다
완전 깜놀..넘 이쁘다 
차기작으로 빨리 보았으면 좋겠어요
실물 그냥 인형임 진짜이목구비 조화가 미친 인형 ㄷㄷ
다 잘 어울리네 
지

뭔가 예쁘다기보다는 아름다운 분위기ㅠㅠ 넘 좋아
세련되어보인다
솔직히 발음하고 발성은 진짜 독보적인거같아
목소리 분위기 천만불
역시 성형미인과는 다른 아우라가 아름다워요 절대 지금 마스크 그대로 연기해주면 좋겠네요 
단아미 고전미 우아미 세련미 다나오네
요즘 이만한 배우가 없는거 같다. 
신인이 엊그제였는데 어느새 탑이 됐어
성형 미인이 낼수없는 무언가가 있네.
기품있게 생긴 외모라는 게 참 어울리는 배우임.
아름답다라던가 분위기가 사람 확 끌어당기는 어떤역을 맡아도 잘 어울리는 듯해요 좋은 배우가 되주세요 
연예인 방송인이 아닌 오랫만에 보는 진짜 배우다!
분위기가 독보적이고 너무 아름답다
예뻐
진짜 예뻐보임 신기함. 
진짜 독보적인 매력인듯
발견한 눈을 칭찬하고 싶은 보석같은 배우 분위기며 연기력이며?
너무 예쁘고 당당하고 기품있다! 
내면의 자기 사랑이 아름다와 보이게 하는 것 같다 
우아하고 고혹적이고 세상흔한 이쁜 미모랑은 다른 특유의 아름다움과 부드러움이있다. 
정말 매략적이더라
와 분위기 하나로 모든걸 씹어드시넵
진짜 이뻐
타고난 분위기는 성형으로도 못따라옴 
연기도 잘해서 좋음
진짜 또래 연기자들 사이에서 독보적인 인물! 
연기도 마스크도! 
앞으로가 더 기대됨!
진짜 연기만 탄탄하면 더 멋있어보임...역시나!
배우중 최고다
연기를 어쩜 그리 잘해
매력잇는배우인거같다.넘예쁘고 귀엽고 톤도 매력적이고..
고급스러운 분위기가 풍겨요..얼굴도 조막만하고 키도 생각보다 크고..잘되어서 너무 좋네요 
저런 분위기는 성형으로도 못만들지. 
어떤 색이든 낼 수 있는 분위기를 갖고있음. 
특유의 소박해보이면서도 고전적인 매력이 엄청난 강점같음.
천의 얼굴이란 게 이런뜻인가보다. 대단한 배우
나이도 어린데 기품이 느껴짐..
특유의 분위기가 넘나 매력적인 자꾸 보고 싶은 배우!
자연스런 마스크에 연기파에 
일단 연기잘하자나. 그리고 본인만의매력이있고
연기 잘하는편..
고급진 비쥬얼그 누구도 못 따라올듯...
연기면 연기 분위기면 분위기 너무 고급지다..
연기자로서

몸 괜찮아요?
각오 센스 노력 재미 다 칭찬함.
거침없는 말에 더 재밌는듯 ㅎㅎ옛날 은지원 생각남 ㅋㅋㅋㅋ
까나리 잔 먹는거보고 열정이 대단하다 느낌. 장청소 시원하게 한듯 한데 위는 괜찮나 싶음.
까나리 먹는거 보고 놀랐어요 방송서 여짓것 보여진 이미지랑 다른 책임감이라 생각할께요 응원해요!
까나리 원샷 대단했음 열심히 하고자 하는 열정에 박수!!식상할 것 같았는 딸이 너무 재미있다네요 
까나리 잔 완전 깜놀...대단하더라밥먹다 내속이 더 안좋던데..진짜 아무도 못할듯어머니 새벽기도 가시고 그 보답으로더 열심히 하는것 같아요..앞으로 응원할게요
까나리카노 잔을 마시는데 우와 응원할께요. 실은 그닥 좋아하지 않았지만 그렇게 열심히 하는 걸 보니 응원하게 되네요. 
깜놀. 첨에 까나리 아닌 줄 알았음. 딘딘 다시 봄. 김종민이 터줏대감으로 계속 나오는 것도 좋았음. 다른 분들은 이단 예능에서 거의 볼 수 없던 분들이라 앞으로 좀더 서로 친숙해지고 적응됐을 때가 기대됨.
남자다잉 화이팅 
너 까나리 잔 다시봤다....
너무 귀여워!! 응원합니다
너무 열심히 하고 분위기 메이커더라
너무 열정적이고 열심히 하는 모습에 감동입니다 승승 장구하세요
너무재밌는데 왜 방송에서많이않나오는지모르겠다 선을 적절히 넘나들며 잘하던데
볼수록 호감 매력 쩌네
다른예능에서는 몰랐는데 엄청 호감이에요!! 박 일 오랜만에 봐서 그런지 너무 재미있어요 앞으로 기대할게요! 한국의 좋은 곳 많이 소개해주세요 새로운 게임들도 기대 할게요
대단. 홧팅!
대충대충할줄 알았는데 진짜 독한듯 의외의모습에 깜놀
막내라인 재밌었어요 
멘트웃긴다ㅋㅋㅋ 순발력좋은데커피 잔연속 어케됨 대단해ㅋ 첫방 괜찮았음
보기 좋더라구요 사람좋아보이더라구요 잘뽑으셧는데요 박 일 멤버들 
성공하자!!
속 괜찬나요?
싫어했는데 열심히 하네ㅋㅋ 지켜볼게요ㅋㅋ
짱이야! 화이팅!
짱이예요 좋은출발이요 
첨엔 그냥 그랬는데 볼수록 괜찮은듯.
최고네요. 다시봤어요. 열씸히하려는 맘이 많이 느껴져서 앞으로도 더욱 응원하고싶네요. 박 일 파이

오랜만에 드라마 다운 드라마를 봤네요 작가님도 감독님도 배우님들도 감사합니다 웃고 울면서 드라마를 봤어요 
오랜만에 드라마 챙겨봤당 너무 재밋었음
오랜만에 만난 인생드라마 였어요
오랜만에 오래 기억될 드라마가 나왔네. 설렘 재미 훈훈 반전 다 갖춘 드라마였다. 나중에 또 생각날 때 봐야지. 이 작가 필력 좋은 듯
오랜만에 최고의 드라마 만나서 너무 행복했어요. 제작진분들 배우님들 최고이십니다 한 동안 여운 갖고 살겠어요 
오랫만에 가슴 따뜻한 드라마였어요
오랜만에 최고의 드라마였습니다 대상받자ㅠㅠ 다른드라마에서보자ㅠㅠ
올해 드라마중 젤 무공해 드라마였음 막장 드라마 속에서
올해 수신료의 가치는 이 드라마 하나로 인정
올해 연기대상과 내년 백상에서도 상 휩쓸길 바라봅니다
올해 첨으로 실시간으로 본 드라마 최고도 부족한 드라마
올해 최고 드라마 ㅠㅠ한회한회 울다 웃다가 감동적이엇다가 ㅜㅜ최고 엿습니다 ㅠㅠ
올해 최고의 드라마
올해 최고의 작품!최고의 배우분들 울고웃고 넘 개운하게봤어요 감사합니다 
올해 연기대상에서 배우님들 다 상받으셨으면 좋겠어요ㅠㅠ한분한분 다 소중해ㅠㅠㅠ
올해 하반기 드라마중 원탑
올해는 힘들고 우울했던 한해였는데 드라마 때문에 행복했습니다 작가님 작품 또 기다릴께요 
올 연말 연기대상은 꼭 봐야겠군 모두에게 대상을...그것이 안된다면 주연배우들이 대표로 대상!!받으면 안될까요??
올 연말엔..오랜만에 정말 한 년만에 연기대상을 봐야겠다 
올 한해 모든 방송사 통틀어 최고의 넘버원 드라마!!
올 해 연기대상은 꼭 지켜보고 싶네요
올간만에 따뜻한 드라마. 최고 
올해 최고의 드라마 레전드가 될 꺼야
올해 연기대상
와 엔딩이 진짜 너무좋았어요 너무 흐뭇하게 보았고 보면서 많은걸 배웠네요
와 그냥 감탄밖에 안나옴
와 증말 나오신 모든 배우님들 진심 연기자들만 모아놨네요 허접한 이상한 애들 하나없이 ... 내용도 ㅠ 정말 간만에 인지 처음인지 할 정도로 웃음 감동 눈물 반성 희망 등 모든게 다 들어가있는 드라마를 봤네요 !!!
와 진짜 이렇게 완벽한드

In [5]:
from konlpy.tag import Okt  
okt = Okt()

In [6]:
token=[]
for sentence in comment_data['comment']:
    temp_X = []
    temp_X = okt.morphs(sentence, stem=True) # 토큰화
    #temp_X = [word for word in temp_X if not word in stopwords] # 불용어 제거
    token.append(temp_X)

In [7]:
print(token[:3])

[['정말', '노래', '대단하다'], ['가창력', '대단하다', '.', '인기', '도', '굉장하다', '.', '연예계', '의', '별', '이', '되다', '같다'], ['노래', '만큼은', '정말', '넘사벽', '맞다', '.', '최고', '맞다', '.']]


# 정수 인코딩 수행

In [8]:
max_words = 35000
tokenizer = Tokenizer(num_words = max_words) # 상위 35,000개의 단어만 보존
tokenizer.fit_on_texts(token) 
token = tokenizer.texts_to_sequences(token)

In [9]:
word_to_index = tokenizer.word_index

In [10]:
vocab_size = len(word_to_index)+1
print('형태소 집합의 크기: {}'.format((vocab_size)))

형태소 집합의 크기: 6684


In [11]:
sequences = list()
for line in normalized_text: # 샘플을 1개씩 가져온다.
    encoded = tokenizer.texts_to_sequences([line])[0] # 각 샘플에 대한 정수 인코딩
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)
print(sequences[:5]) 
print(len(sequences))

[[18, 49], [18, 825], [18, 825, 307], [18, 825, 307, 19], [18, 825, 307, 19, 307]]
12739


In [12]:
max_len=max(len(l) for l in sequences)
print('샘플의 최대 길이 : {}'.format(max_len))

샘플의 최대 길이 : 31


In [13]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')
print(sequences[:5])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  18  49]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  18 825]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0  18 825 307]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0  18 825 307  19]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0  18 825 307  19 307]]


In [14]:
sequences = np.array(sequences)
X = sequences[:,:-1]
y = sequences[:,-1]
print(X[:3])
print(y[:3])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  18]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  18]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0  18 825]]
[ 49 825 307]


# 원핫 인코딩

In [15]:
from tensorflow.keras.utils import to_categorical

In [16]:
y = to_categorical(y, num_classes=vocab_size)
print(y[:3])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


# LSTM

In [17]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM

In [18]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = max_len - 1))
model.add(LSTM(128))
model.add(Dense(vocab_size, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
model.fit(X, y, epochs = 20, batch_size = 32, validation_split = 0.1)

Train on 11465 samples, validate on 1274 samples
Epoch 1/20
11465/11465 [==============================] - 27s 2ms/sample - loss: 6.7658 - accuracy: 0.0430 - val_loss: 6.3701 - val_accuracy: 0.0565
Epoch 2/20
11465/11465 [==============================] - 23s 2ms/sample - loss: 6.3996 - accuracy: 0.0442 - val_loss: 6.3866 - val_accuracy: 0.0565
Epoch 3/20
11465/11465 [==============================] - 24s 2ms/sample - loss: 6.3282 - accuracy: 0.0441 - val_loss: 6.3931 - val_accuracy: 0.0581
Epoch 4/20
11465/11465 [==============================] - 22s 2ms/sample - loss: 6.2829 - accuracy: 0.0467 - val_loss: 6.3799 - val_accuracy: 0.0542
Epoch 5/20
11465/11465 [==============================] - 23s 2ms/sample - loss: 6.2466 - accuracy: 0.0519 - val_loss: 6.3863 - val_accuracy: 0.0565
Epoch 6/20
11465/11465 [==============================] - 23s 2ms/sample - loss: 6.2200 - accuracy: 0.0522 - val_loss: 6.3875 - val_accuracy: 0.0549
Epoch 7/20
11465/11465 [==============================] -

In [19]:
model.save('C:\\Users\\user\\Documents\\GitHub\\grad_project\\website\\model_create.h5')

# 문장 생성

In [37]:
def sentence_generation(model, t, current_word, n): # 모델, 토크나이저, 현재 단어, 반복할 횟수
    init_word = current_word # 처음 들어온 단어도 마지막에 같이 출력하기위해 저장
    sentence = ''
    for _ in range(n): # n번 반복
        encoded = t.texts_to_sequences([current_word])[0] # 현재 단어에 대한 정수 인코딩
        encoded = pad_sequences([encoded], maxlen=30, padding='pre') # 데이터에 대한 패딩
        result = model.predict_classes(encoded, verbose=0)# 입력한 X(현재 단어)에 대해서 y를 예측하고 y(예측한 단어)를 result에 저장.
        for word, index in t.word_index.items(): 
            if index == result: # 만약 예측한 단어와 인덱스와 동일한 단어가 있다면
                break # 해당 단어가 예측 단어이므로 break
        current_word = current_word + ' '  + word # 현재 단어 + ' ' + 예측 단어를 현재 단어로 변경
        sentence = sentence + ' ' + word # 예측 단어를 문장에 저장
    # for문이므로 이 행동을 다시 반복
    sentence = init_word + sentence
    return sentence

In [38]:
clean_sen = []
for i in range(0,10):
    sentence = sentence_generation(model, tokenizer, '나는', i)
    clean_sen.append(sentence)
    i += 1
print(clean_sen[9])

나는 너무 너무 너무 너무 너무 너무 너무 너무 너무
